name: 'retail_weather'
version: '1.0.0'

profile: 'retail_weather'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# models:
#   retail_weather:
#     staging:
#       +materialized: view
#       +schema: staging
#     marts:
#       +materialized: table
#       +schema: marts

models:
  retail_weather:
    staging:
      +materialized: view
    marts:
      +materialized: table
      star_schema:
        +materialized: table
